# Generated by Django 4.2.11 on 2026-08-25 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_order', 'New Order'), ('payment_received', 'Payment Received'), ('large_order', 'Large Order Alert'), ('order_cancelled', 'Order Cancelled'), ('contact_submission', 'Contact Submission'), ('booking_inquiry', 'Booking Inquiry'), ('low_stock', 'Low Stock'), ('daily_summary', 'Daily Summary'), ('weekly_summary', 'Weekly Summary'), ('monthly_summary', 'Monthly Summary')], max_length=30),
        ),
    ]
