from django.urls import path

from .views import (
    AdminActivityLogsView,
    AdminBookingInquiriesView,
    AdminBookingInquiryDetailView,
    AdminContactListView,
    AdminCurrencySettingsView,
    AdminEventServiceDetailView,
    AdminEventServicesView,
    AdminHeroImagesView,
    AdminHeroImageView,
    AdminNewsletterListView,
    AdminNewsletterDetailView,
    AdminSaleAnnouncementsView,
    AdminSaleAnnouncementDetailView,
    AdminSettingsView,
    AdminTestimonialsView,
    AdminTestimonialDetailView,
    AdminTrainingProgramDetailView,
    AdminTrainingProgramsView,
    AdminWhyChooseItemsView,
    AdminWhyChooseItemDetailView,
    BookingSubmitView,
    ContactSubmitView,
    CurrencySettingsView,
    EventServiceTypesView,
    HeroImagesView,
    NewsletterSubscribeView,
    SaleAnnouncementsView,
    SiteAssetsView,
    SiteSettingsView,
    TestimonialListView,
    TrainingProgramsView,
    WhyChooseListView,
)

urlpatterns = [
    path('settings/', SiteSettingsView.as_view(), name='site-settings'),
    path('currency-settings/', CurrencySettingsView.as_view(), name='currency-settings'),
    path('sale-announcements/', SaleAnnouncementsView.as_view(), name='sale-announcements'),
    path('assets/', SiteAssetsView.as_view(), name='site-assets'),
    path('testimonials/', TestimonialListView.as_view(), name='testimonials'),
    path('hero-images/', HeroImagesView.as_view(), name='hero-images'),
    path('why-choose/', WhyChooseListView.as_view(), name='why-choose'),
    path('event-services/', EventServiceTypesView.as_view(), name='event-services'),
    path('training-programs/', TrainingProgramsView.as_view(), name='training-programs'),
    path('bookings/', BookingSubmitView.as_view(), name='booking-submit'),
    path('contact/', ContactSubmitView.as_view(), name='contact-submit'),
    path('newsletter/', NewsletterSubscribeView.as_view(), name='newsletter-subscribe'),
    path('admin/contacts/', AdminContactListView.as_view(), name='admin-contacts'),
    path('admin/bookings/', AdminBookingInquiriesView.as_view(), name='admin-bookings'),
    path('admin/bookings/<int:pk>/', AdminBookingInquiryDetailView.as_view(), name='admin-booking-detail'),
    path('admin/event-services/', AdminEventServicesView.as_view(), name='admin-event-services'),
    path('admin/event-services/<int:pk>/', AdminEventServiceDetailView.as_view(), name='admin-event-service-detail'),
    path('admin/training-programs/', AdminTrainingProgramsView.as_view(), name='admin-training-programs'),
    path('admin/training-programs/<int:pk>/', AdminTrainingProgramDetailView.as_view(), name='admin-training-program-detail'),
    path('admin/newsletter/', AdminNewsletterListView.as_view(), name='admin-newsletter'),
    path('admin/newsletter/<int:pk>/', AdminNewsletterDetailView.as_view(), name='admin-newsletter-detail'),
    path('admin/settings/', AdminSettingsView.as_view(), name='admin-settings'),
    path('admin/currency-settings/', AdminCurrencySettingsView.as_view(), name='admin-currency-settings'),
    path('admin/sale-announcements/', AdminSaleAnnouncementsView.as_view(), name='admin-sale-announcements'),
    path(
        'admin/sale-announcements/<int:pk>/',
        AdminSaleAnnouncementDetailView.as_view(),
        name='admin-sale-announcement-detail',
    ),
    path('admin/testimonials/', AdminTestimonialsView.as_view(), name='admin-testimonials'),
    path('admin/testimonials/<int:pk>/', AdminTestimonialDetailView.as_view(), name='admin-testimonial-detail'),
    path('admin/hero-images/', AdminHeroImagesView.as_view(), name='admin-hero-images'),
    path('admin/hero-images/<int:pk>/', AdminHeroImageView.as_view(), name='admin-hero-image-detail'),
    path('admin/why-choose/', AdminWhyChooseItemsView.as_view(), name='admin-why-choose'),
    path('admin/why-choose/<int:pk>/', AdminWhyChooseItemDetailView.as_view(), name='admin-why-choose-detail'),
    path('admin/activity-logs/', AdminActivityLogsView.as_view(), name='admin-activity-logs'),
]
