# Generated by Django 4.2.11 on 2026-08-25 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0013_rebrand_tasty_fingers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroimage',
            name='category',
            field=models.CharField(blank=True, default='COLLECTION', help_text='Small label on the homepage hero carousel card (e.g. JOLLOF, SOUPS)', max_length=80),
        ),
        migrations.AlterField(
            model_name='saleannouncement',
            name='end_date',
            field=models.DateField(blank=True, help_text='Promo end date', null=True),
        ),
        migrations.AlterField(
            model_name='saleannouncement',
            name='start_date',
            field=models.DateField(blank=True, help_text='Promo start date', null=True),
        ),
    ]
