# Generated by Django 4.2.11 on 2026-08-25 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_fringe_and_flash_sale_start'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Food Category', 'verbose_name_plural': 'Food Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Meal', 'verbose_name_plural': 'Meals'},
        ),
        migrations.AlterModelOptions(
            name='productreview',
            options={'ordering': ['-created_at'], 'verbose_name': 'Meal Review', 'verbose_name_plural': 'Meal Reviews'},
        ),
        migrations.AlterField(
            model_name='product',
            name='density',
            field=models.CharField(blank=True, help_text='Portion or size label, e.g. Small, Medium, Large, Family Pack', max_length=50, verbose_name='Portion / Size'),
        ),
        migrations.AlterField(
            model_name='product',
            name='flash_sale_end_at',
            field=models.DateTimeField(blank=True, help_text='When this meal’s flash sale ends on the storefront.', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='flash_sale_start_at',
            field=models.DateTimeField(blank=True, help_text='When this meal’s flash sale becomes active on the storefront.', null=True),
        ),
    ]
