# Generated by Django 4.2.11 on 2026-08-26 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='flash_sale_end_at',
            field=models.DateTimeField(blank=True, help_text='When this deal ends on the storefront.', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='flash_sale_start_at',
            field=models.DateTimeField(blank=True, help_text='When this deal becomes active on the storefront.', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_bestseller',
            field=models.BooleanField(default=False, verbose_name='Popular Meal'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name="Chef's Pick"),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_flash_sale',
            field=models.BooleanField(default=False, verbose_name="Today's Deal"),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_new_arrival',
            field=models.BooleanField(default=False, verbose_name='Tasty Combo'),
        ),
    ]
